repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.5.7
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --extend-select, I, --fix ]
      types_or: [ python, pyi, jupyter ]
      exclude: "xlstm_local/.*"
    # Run the formatter.
    - id: ruff-format
      exclude: "xlstm_local/.*"
