name: slcde
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.12.5
  - pytorch=2.4.0
  - torchvision=0.19.0
  - torchaudio=2.4.0
  - pytorch-cuda=12.4
  - pandas=2.2.2
  - pre-commit=3.8.0
  - pytest=8.3.2